export enum Icons {
  download = 'download',
  event_note = 'event_note',
  person = 'person',
  people = 'people',
  list_alt = 'list_alt',
  assignment_turned_in = 'assignment_turned_in',
  timelapse = 'timelapse',
  money = 'money',
  menu = 'menu',
  error = 'error',
  check = 'check',
  visibility = 'visibility',
  visibility_off = 'visibility_off',
  edit = 'edit',
  delete = 'delete',
  add_box = 'add_box',
  close = 'close',
  delete_forever = 'delete_forever',
  control_point_duplicate = 'control_point_duplicate',
  keyboard_arrow_right = 'keyboard_arrow_right',
  keyboard_arrow_left = 'keyboard_arrow_left',
  settings = 'settings',
  info = 'info',
}
